PRAGMA foreign_keys = ON;

--
CREATE TABLE EB_INB_F (
BEN_NIR_IDT TEXT NOT NULL PRIMARY KEY,
BEN_NAI_ANN TEXT NOT NULL,
BEN_RES_DPT TEXT NOT NULL ,
BEN_SEX_COD INTEGER NOT NULL ,
BEN_DCD_AME TEXT NOT NULL ,

CHECK((length(BEN_NIR_IDT) == 17) or length(BEN_NIR_IDT) == 16),
CHECK(length(BEN_NAI_ANN) == 4),
CHECK(length(BEN_RES_DPT) == 3),
CHECK (BEN_SEX_COD == 1 or BEN_SEX_COD == 2),
CHECK ((length(BEN_DCD_AME) == 6) or length(BEN_DCD_AME) == 0)
);


CREATE TABLE EB_IMB_R (
BEN_NIR_IDT TEXT NOT NULL,
IMB_ALD_NUM INTEGER NOT NULL,
IMB_ALD_DTD DATE NOT NULL,
IMB_ALD_DTF DATE NOT NULL,
IMB_ETM_NAT INTEGER NOT NULL,
MED_MTF_COD TEXT NOT NULL, 


CONSTRAINT fk_ben_nir_idt FOREIGN KEY (BEN_NIR_IDT) REFERENCES EB_INB_F(BEN_NIR_IDT) ON DELETE CASCADE,
CONSTRAINT fk_med_mtf_cod FOREIGN KEY(MED_MTF_COD) REFERENCES IR_CIM_V(CIM_COD) ON DELETE CASCADE,
CONSTRAINT fk_imb_ald_num FOREIGN KEY(IMB_ALD_NUM) REFERENCES IR_ALD_V(ALD_030_COD) ON DELETE CASCADE
);

--
CREATE TABLE IR_CIM_V (
CIM_COD TEXT NOT NULL PRIMARY KEY,
CIM_LIB TEXT NOT NULL,
ALD_030_COD INTEGER NOT NULL

CHECK (length(CIM_COD) <= 6),
CHECK (length(CIM_LIB) <= 255),
CHECK (ALD_030_COD >= 0 and ALD_030_COD <= 99)
);

--
CREATE TABLE IR_ALD_V (
ALD_030_COD INTEGER NOT NULL PRIMARY KEY,
ALD_030_LIB TEXT NOT NULL

CHECK (ALD_030_COD >= 0 and ALD_030_COD <= 99),
CHECK (length(ALD_030_LIB) <= 130)
);

--
CREATE TABLE ES_PRS_F(
CLE_TEC_JNT TEXT NOT NULL PRIMARY KEY,
BEN_NIR_IDT TEXT NOT NULL,
EXE_SOI_DTD DATE NOT NULL,
EXE_SOI_DTF DATE NOT NULL,
PFS_PRE_CRY TEXT NOT NULL,
PRS_NAT_REF INTEGER,
FLX_DIS_DTD DATE NOT NULL,
PSE_ACT_SPE INTEGER NOT NULL,
BEN_CMU_TOP TEXT NOT NULL,
PRE_PRE_DTD DATE NOT NULL,
PRS_ACT_QTE INTEGER NOT NULL,

CHECK (length(CLE_TEC_JNT) <= 77 and length(CLE_TEC_JNT) >= 70),
CHECK (length(PFS_PRE_CRY) <= 32 and length(PFS_PRE_CRY) >= 25 ),
CHECK (length(BEN_CMU_TOP) == 1),
CHECK(PRS_ACT_QTE == 1 or PRS_ACT_QTE == 0),
CONSTRAINT fk_ben_nir_idt FOREIGN KEY (BEN_NIR_IDT) REFERENCES EB_INB_F(BEN_NIR_IDT) ON DELETE CASCADE,
CONSTRAINT fk_prs_nat_ref FOREIGN KEY (PRS_NAT_REF) REFERENCES IR_NAT_V(PRS_NAT) ON DELETE CASCADE

);
--
CREATE TABLE IR_NAT_V (
PRS_NAT INTEGER NOT NULL PRIMARY KEY,
PRS_NAT_LIB TEXT NOT NULL

CHECK ((PRS_NAT >= 1000 AND PRS_NAT <= 9999) or PRS_NAT == 0),
CHECK (length(PRS_NAT_LIB) <= 150)
);

--
CREATE TABLE ES_CAM_F (
CLE_TEC_JNT TEXT PRIMARY KEY,
BEN_NIR_IDT TEXT,
EXE_SOI_DTD TEXT NOT NULL,
EXE_SOI_DTF DATE NOT NULL,
PFS_PRE_CRY TEXT NOT NULL,
PRS_NAT_REF INTEGER,
FLX_DIS_DTD DATE NOT NULL,
CAM_PRS_IDE TEXT NOT NULL,
CAM_ACT_QSN INTEGER NOT NULL,

CONSTRAINT fk_jnt FOREIGN KEY (CLE_TEC_JNT) REFERENCES ES_PRS_F(CLE_TEC_JNT) ON DELETE CASCADE,
CONSTRAINT fk_ben_nir_idt FOREIGN KEY(BEN_NIR_IDT) REFERENCES EB_INB_F(BEN_NIR_IDT) ON DELETE CASCADE,
CONSTRAINT fk_prs_nat_ref FOREIGN KEY(PRS_NAT_REF) REFERENCES IR_NAT_V(PRS_NAT) ON DELETE CASCADE
);

--
CREATE TABLE ES_BIO_F(
CLE_TEC_JNT TEXT PRIMARY KEY,
BEN_NIR_IDT TEXT,
EXE_SOI_DTD TEXT NOT NULL,
EXE_SOI_DTF DATE NOT NULL,
PFS_PRE_CRY TEXT NOT NULL,
PRS_NAT_REF INTEGER,
FLX_DIS_DTD DATE NOT NULL,
BIO_PRS_IDE INTEGER,
BIO_ACT_QSN INTEGER NOT NULL,

CONSTRAINT fk_jnt FOREIGN KEY (CLE_TEC_JNT) REFERENCES ES_PRS_F(CLE_TEC_JNT) ON DELETE CASCADE,
CONSTRAINT fk_ben_nir_idt FOREIGN KEY(BEN_NIR_IDT) REFERENCES EB_INB_F(BEN_NIR_IDT) ON DELETE CASCADE,
CONSTRAINT fk_prs_nat_ref FOREIGN KEY(PRS_NAT_REF) REFERENCES IR_NAT_V(PRS_NAT) ON DELETE CASCADE,
CONSTRAINT fk_bio_prs_ide FOREIGN KEY(BIO_PRS_IDE) REFERENCES IR_BIO_R(BIO_PRS_IDE) ON DELETE CASCADE
);

--
CREATE TABLE ES_PHA_F(
CLE_TEC_JNT TEXT PRIMARY KEY,
BEN_NIR_IDT TEXT,
EXE_SOI_DTD TEXT NOT NULL,
EXE_SOI_DTF DATE NOT NULL,
PFS_PRE_CRY TEXT NOT NULL,
PRS_NAT_REF INTEGER,
FLX_DIS_DTD DATE NOT NULL,
PHA_PRS_IDE INTEGER,
PHA_PRS_C13 INTEGER NOT NULL,
PHA_ACT_QSN INTEGER NOT NULL,

CONSTRAINT fk_jnt FOREIGN KEY (CLE_TEC_JNT) REFERENCES ES_PRS_F(CLE_TEC_JNT) ON DELETE CASCADE,
CONSTRAINT fk_ben_nir_idt FOREIGN KEY(BEN_NIR_IDT) REFERENCES EB_INB_F(BEN_NIR_IDT) ON DELETE CASCADE,
CONSTRAINT fk_prs_nat_ref FOREIGN KEY(PRS_NAT_REF) REFERENCES IR_NAT_V(PRS_NAT) ON DELETE CASCADE,
CONSTRAINT fk_pha_prs_ide FOREIGN KEY(PHA_PRS_IDE) REFERENCES IR_PHA_R(PHA_PRS_IDE) ON DELETE CASCADE
);

--
CREATE TABLE IR_BIO_R (
BIO_PRS_IDE INTEGER PRIMARY KEY,
BIO_INF_LIB TEXT NOT NULL
);

--
CREATE TABLE IR_PHA_R(
PHA_ACT_C07 TEXT NOT NULL,
PHA_CIP_C13 INTEGER NOT NULL,
PHA_CIP_UCD INTEGER NOT NULL,
PHA_CND_TOP TEXT NOT NULL,
PHA_DOS_PRA_DSES TEXT NOT NULL,
PHA_DOS_UNT_DSES TEXT NOT NULL,
PHA_FRM_COD TEXT NOT NULL,
PHA_FRM_LIB TEXT NOT NULL,
PHA_LAB_NOM TEXT NOT NULL,
PHA_MED_COM TEXT NOT NULL,
PHA_MED_NOM TEXT NOT NULL,
PHA_NOM_COURT TEXT NOT NULL,
PHA_NOM_PA  TEXT NOT NULL,
PHA_PRS_IDE INTEGER NOT NULL PRIMARY KEY,
PHA_UNT_NBR_DSES TEXT NOT NULL
);


CREATE TABLE T_MCO18C (
BEN_NIR TEXT NOT NULL,
ETA_NUM TEXT NOT NULL,
RSA_NUM TEXT NOT NULL,
EXE_SOI_DTD DATE NOT NULL,
EXE_SOI_DTF DATE NOT NULL,

CONSTRAINT pk_rsa_eta PRIMARY KEY (ETA_NUM,RSA_NUM),
CONSTRAINT fk_ben_nir FOREIGN KEY(BEN_NIR) REFERENCES EB_INB_F(BEN_NIR_IDT) ON DELETE CASCADE
);

CREATE TABLE T_MCO18A (
ETA_NUM TEXT,
RSA_NUM TEXT,
CDC_ACT TEXT,

CONSTRAINT fk_eta_rsa FOREIGN KEY(ETA_NUM,RSA_NUM) REFERENCES T_MCO18C(ETA_NUM,RSA_NUM) ON DELETE CASCADE,
CONSTRAINT fk_cdc_act FOREIGN KEY(CDC_ACT) REFERENCES XC_ACT_R(ACT_COD) ON DELETE CASCADE
);

CREATE TABLE XC_ACT_R (
ACT_COD TEXT NOT NULL PRIMARY KEY,
ACT_LIB_CRT TEXT NOT NULL,
ACT_LIB_LNG TEXT NOT NULL
);

-- T_MCO18 (C-A-B-D)
CREATE TABLE T_MCO18B (
ETA_NUM TEXT,
RSA_NUM TEXT,
GRG_GHM TEXT NOT NULL,
ENT_MOD TEXT NOT NULL,
ENT_PRV TEXT,
SOR_MOD TEXT NOT NULL,
SOR_DES TEXT NOT NULL,
SEJ_NBJ INTEGER NOT NULL,
DGN_PAL TEXT NOT NULL,
DGN_REL TEXT NOT NULL,

CONSTRAINT fk_eta_rsa FOREIGN KEY(ETA_NUM,RSA_NUM) REFERENCES T_MCO18C(ETA_NUM,RSA_NUM) ON DELETE CASCADE

);

CREATE TABLE T_MCO18D (
ETA_NUM TEXT,
RSA_NUM TEXT, 
ASS_DGN TEXT NOT NULL,

CONSTRAINT fk_eta_rsa FOREIGN KEY(ETA_NUM,RSA_NUM) REFERENCES T_MCO18C(ETA_NUM,RSA_NUM) ON DELETE CASCADE

);

-- T_MCO19(C-A-B-D)
CREATE TABLE T_MCO19C (
BEN_NIR TEXT NOT NULL,
ETA_NUM TEXT NOT NULL,
RSA_NUM TEXT NOT NULL,
EXE_SOI_DTD DATE NOT NULL,
EXE_SOI_DTF DATE NOT NULL,

CONSTRAINT pk_rsa_eta PRIMARY KEY (ETA_NUM, RSA_NUM),
CONSTRAINT fk_ben_nir FOREIGN KEY(BEN_NIR) REFERENCES EB_INB_F(BEN_NIR_IDT) ON DELETE CASCADE


);

CREATE TABLE T_MCO19A (
ETA_NUM TEXT,
RSA_NUM TEXT,
CDC_ACT TEXT,

CONSTRAINT fk_eta_rsa FOREIGN KEY(ETA_NUM,RSA_NUM) REFERENCES T_MCO19C(ETA_NUM,RSA_NUM) ON DELETE CASCADE,
CONSTRAINT fk_cdc_act FOREIGN KEY(CDC_ACT) REFERENCES XC_ACT_R(ACT_COD) ON DELETE CASCADE
);

CREATE TABLE T_MCO19B (
ETA_NUM TEXT,
RSA_NUM TEXT,
GRG_GHM TEXT NOT NULL,
ENT_MOD TEXT NOT NULL,
ENT_PRV TEXT,
SOR_MOD TEXT NOT NULL,
SOR_DES TEXT NOT NULL,
SEJ_NBJ INTEGER NOT NULL,
DGN_PAL TEXT NOT NULL,
DGN_REL TEXT NOT NULL,

CONSTRAINT fk_eta_rsa FOREIGN KEY(ETA_NUM,RSA_NUM) REFERENCES T_MCO19C(ETA_NUM,RSA_NUM) ON DELETE CASCADE
);

CREATE TABLE T_MCO19D (
ETA_NUM TEXT,
RSA_NUM TEXT, 
ASS_DGN TEXT NOT NULL,

CONSTRAINT fk_eta_rsa FOREIGN KEY(ETA_NUM,RSA_NUM) REFERENCES T_MCO19C(ETA_NUM,RSA_NUM) ON DELETE CASCADE
);

-- T_MCO20(C-A-B-D)
CREATE TABLE T_MCO20C (
BEN_NIR TEXT NOT NULL,
ETA_NUM TEXT NOT NULL,
RSA_NUM TEXT NOT NULL,
EXE_SOI_DTD DATE NOT NULL,
EXE_SOI_DTF DATE NOT NULL,

CONSTRAINT pk_rsa_eta PRIMARY KEY (ETA_NUM, RSA_NUM),
CONSTRAINT fk_ben_nir FOREIGN KEY(BEN_NIR) REFERENCES EB_INB_F(BEN_NIR_IDT) ON DELETE CASCADE
);

CREATE TABLE T_MCO20A (
ETA_NUM TEXT,
RSA_NUM TEXT,
CDC_ACT TEXT,

CONSTRAINT fk_eta_rsa FOREIGN KEY(ETA_NUM,RSA_NUM) REFERENCES T_MCO20C(ETA_NUM,RSA_NUM) ON DELETE CASCADE,
CONSTRAINT fk_cdc_act FOREIGN KEY(CDC_ACT) REFERENCES XC_ACT_R(ACT_COD) ON DELETE CASCADE
);

CREATE TABLE T_MCO20B (
ETA_NUM TEXT,
RSA_NUM TEXT,
GRG_GHM TEXT NOT NULL,
ENT_MOD TEXT NOT NULL,
ENT_PRV TEXT,
SOR_MOD TEXT NOT NULL,
SOR_DES TEXT NOT NULL,
SEJ_NBJ INTEGER NOT NULL,
DGN_PAL TEXT NOT NULL,
DGN_REL TEXT NOT NULL,

CONSTRAINT fk_eta_rsa FOREIGN KEY(ETA_NUM,RSA_NUM) REFERENCES T_MCO20C(ETA_NUM,RSA_NUM) ON DELETE CASCADE
);

CREATE TABLE T_MCO20D (
ETA_NUM TEXT,
RSA_NUM TEXT, 
ASS_DGN TEXT NOT NULL,

CONSTRAINT fk_eta_rsa FOREIGN KEY(ETA_NUM,RSA_NUM) REFERENCES T_MCO20C(ETA_NUM,RSA_NUM) ON DELETE CASCADE
);
